### ISSUE TITLE
Basic Demo Page

### ISSUE THREAD

**Issue by EddieDemon** [abjerner/Skybrud.Social.Umbraco#11]
Hi,

I read a post of 2014 regarding no time for creating documentation. As far as I can see, there's still nothing.

Could you then - for the sake of spending less time Googling for nothing - create a demo project that goes over everything? For example, I'm currently in a struggle to add the Authenticate button in my template. This should be the least advanced to do. The current documentation assumes you're already logged in, but there's no login documentation.

I'd love to use the plug-in, but it's hard to start with.

**Comment by abjerner** [comment]
@MusicDemon Since you're mentioning your template, I'm assuming your'e trying to implement login for your visitors on your actual website? `Skybrud.Social.Umbraco` is more targeted the Umbraco backoffice, so it seems that you just need `Skybrud.Social`.

`Skybrud.Social` has it's own website - http://skybrud.social/ - with documentation (again, there could be more and better examples, but at least it's a start). Eg. if you're trying to setup an authentication page for Facebook, there is some documentation on this page: http://social.skybrud.dk/facebook/authentication/user-access-token/

I also have an older Gist for Facebook authentication here: https://gist.github.com/abjerner/70c1b2af2b3ea480e353

**Comment by EddieDemon** [comment]
I see, I'll look into it! Thank you!
